fixed issue with Kooapp for false positive #1493
sherlock-project/sherlock pull request #1494
Opened 2022-10-02 14:03 UTC by keder-code-hash

- Fixed The issue with False positive for KOOAPP
- Updated URL for searching

2022-10-03 08:17 UTC, sdushantha commented
This PR does not solve the false positive. You are using the the search query endpoint and that endpoint does not return an `errorMsg` of "Invalid Profile"

2022-10-03 08:26 UTC, keder-code-hash commented
> This PR does not solve the false positive. You are using the the search query endpoint and that endpoint does not return an `errorMsg` of "Invalid Profile"

Hey, Siddharth I observed the Kooapp API call. The/profile/{} won't give us the actual profile and There is no way of checking a particular API call for a particular platform in sherlock. I mean for kooapp,  I can make an API call to check the existence of any user and then we can return his profile details. But I think this type of facility is not available for this project. Can we add that by changing the design pattern to adapter one?
Or else in the data.json, we can associate a function for checking too for a particular platform.

2022-10-03 08:28 UTC, keder-code-hash commented
Please let me know If any other way I can do it. Though for many other profiles we have to make a call for checking the existence of a user. In sherlock.py it is being checked whether the response is returning the correct status or not. Though many platforms do not support the status code properly such as Kooapps. The just do it their own way.

2022-10-03 08:29 UTC, keder-code-hash commented
If we can update the pattern a little bit it would be more feasible I think. What do u say?

2022-10-03 08:37 UTC, sdushantha commented
I did some digging and found an API endpoint: `https://www.kooapp.com/apiV1/users/handle/USERNAME_HERE/valid`

```console
$ curl https://www.kooapp.com/apiV1/users/handle/b23432ob/valid
{"status":"SUCCESS","message":"handle b23432ob is available"}

$ curl https://www.kooapp.com/apiV1/users/handle/bob/valid
{"status":"ERROR","message":"handle bob already taken"}
```

Maybe you could use this

2022-10-03 08:40 UTC, keder-code-hash commented
> I did some digging and found an API endpoint: `https://www.kooapp.com/apiV1/users/handle/USERNAME_HERE/valid`
> 
> ```
> $ curl https://www.kooapp.com/apiV1/users/handle/b23432ob/valid
> {"status":"SUCCESS","message":"handle b23432ob is available"}
> 
> $ curl https://www.kooapp.com/apiV1/users/handle/bob/valid
> {"status":"ERROR","message":"handle bob already taken"}
> ```
> 
> Maybe you could use this

Yeah. Thanks for your reply.
I will change it.

2022-10-03 10:54 UTC, keder-code-hash commented
I have added probeUrl as the checking one.
pl check it once. @sdushantha

2022-10-04 07:26 UTC, sdushantha requested changes

2022-10-04 07:26 UTC, sdushantha commented on sherlock/resources/data.json
> +    "errorMsg": "handle {} is available",
Two minor issues here:
1. "is available" is not an `errorMsg`. "already taken" would be an error message as that is the message for when a username is not found
2. I see that you have used `{}` in the `errorMsg`. Sherlock won't format the string with the username. So it is better to just use `already taken` as the `errorMsg`.

In other words, replace the value for `errorMsg` with `already taken`

2022-10-15 23:57 UTC, sdushantha commented on sherlock/resources/data.json
> +    "errorMsg": "handle {} is available",
Sorry my bad. It should just be `is available`

2022-10-16 00:01 UTC, sdushantha approved these changes

2022-10-16 00:01 UTC, merged