Add support for Monkeytype
sherlock-project/sherlock pull request #1655
Opened 2023-01-02 12:39 UTC by a-r-r-o-w

Added support for https://monkeytype.com/.

[Monkeytype](https://monkeytype.com/) is a famous website for typing tests to improve typing skills, competing in leaderboards, etc. with a clean minimalistic interface.

Please let me know if any additional information/changes are required.

2023-01-10 18:21 UTC, z1nc0r3 requested changes
shouldn't the URL = "https://monkeytype.com/profile/{}" ?

2023-01-11 12:26 UTC, a-r-r-o-w commented
IIRC, I did try out using that with error type detection as message. When you send a request to https://monkeytype.com/profile/{}, it internally makes a call to https://api.monkeytype.com/users/{}/profile which returns all data related to the profile if it exists and otherwise returns an error message which is displayed on the main site as "User {} not found". Irrespective of whether it exists or not, the status_code is 200 for the main site `/profile/{}` endpoint and so that definitely cannot be used. I think using their API to perform the check is, arguably, the best way of detection.

Could you elaborate how the detection methods in sherlock could work if we used https://monkeytype.com/profile/{}?

2023-01-11 12:54 UTC, a-r-r-o-w commented
I just realised that we could use the `urlProbe` parameter for detection and let URL be the actual profile url to direct to instead of the API url that gets displayed when a match is found.

2023-02-04 17:52 UTC, sdushantha commented
Awesome! Everything looks good, I'll merge this right away :)

2023-02-04 17:52 UTC, sdushantha approved these changes

2023-02-04 17:52 UTC, merged