Increment minor version (0.15.0)
sherlock-project/sherlock pull request #2191
Opened 2024-06-25 04:16 UTC by ppfeister

2024-06-29 03:50 UTC, ppfeister commented
Added to staging staging/0.15.0rc0

2024-07-01 16:37 UTC, sdushantha requested changes

2024-07-01 16:37 UTC, sdushantha commented on sherlock/__init__.py
> +forgeApiLatestReleaseUrl = "https://api.github.com/repos/sherlock-project/sherlock/releases/latest"
Since we use snake_case across the project, we should use snake_case here as well

2024-07-01 16:37 UTC, sdushantha commented on sherlock/sherlock.py
> +        latestRemoteTag = latestReleaseJsonData["tag_name"]
See previous comment about snake_case

2024-07-08 07:32 UTC, sdushantha approved these changes

2024-07-08 09:41 UTC, merged