Remove not needed `apt-get update` in Dockerfile
sherlock-project/sherlock pull request #2272
Opened 2024-08-26 18:37 UTC by PeterDaveHello

There's no need to wait and waste the time and bandwidth to wait for `apt-get update` for `pip3 install` ;)

2024-08-27 20:49 UTC, Cur519 approved these changes

2024-08-28 02:51 UTC, ppfeister approved these changes
Good catch. Must be left over from quite a few revisions ago and not at all needed anymore.

2024-08-28 02:51 UTC, merged

2024-09-03 23:47 UTC, Cur519 reviewed
Thank you guys for all your knowledge

2024-12-05 18:51 UTC, Zulu-1540 requested changes
[]() hackers