add v0.dev to data.json
sherlock-project/sherlock pull request #2286
Opened 2024-09-04 20:07 UTC by sk337

add v0.dev to data.json

2024-09-05 19:47 UTC, ppfeister requested changes
The `url` just points to the homepage and has no {} for substituting in a username, nor is there any request data provided as an alternative. This does not appear to check any username, and would return 200 for all queries to the homepage.

The `username_unclaimed` key is also long deprecated, and this will fail schema validation.

2024-09-05 20:07 UTC, sk337 commented
> The `url` just points to the homepage and has no {} for substituting in a username, nor is there any request data provided as an alternative. This does not appear to check any username, and would return 200 for all queries to the homepage.
> 
> The `username_unclaimed` key is also long deprecated, and this will fail schema validation.

fixed the URL and the deprecated field

2024-09-05 20:21 UTC, ppfeister commented on sherlock_project/resources/data.json
> +    "errorMessage": "404 - Page Not Found",
```suggestion
    "errorMsg": "404 - Page Not Found",
```

2024-09-05 20:22 UTC, ppfeister commented on sherlock_project/resources/data.json
> +    "errorMessage": "404 - Page Not Found",
Note that you can test against the schema locally via `tox`

2024-09-05 20:23 UTC, ppfeister commented
Are you aware of any request method that will return a different status code rather than needing an error message? While messages are acceptable, they're a bit of a last resort as they cause problems with l10n

2024-09-05 20:28 UTC, sk337 commented
> Are you aware of any request method that will return a different status code rather than needing an error message? While messages are acceptable, they're a bit of a last resort as they cause problems with l10n

I did some testing and noticed that invalid users return 200 will do more testing didn't check for that in the start

2024-09-05 20:38 UTC, ppfeister commented
No worries if not. Status codes are preferred but sometimes it's not that easy.

Once the suggested change to errorMsg is made, it should be compliant with the schema. Just gotta make sure the error message works once it's valid and able to be tested.

If you're testing locally, you can point sherlock to your own file with `--json` as well

2025-02-03 07:55 UTC, ppfeister approved these changes

2025-02-03 07:59 UTC, ppfeister requested changes

2025-02-03 07:59 UTC, ppfeister commented on sherlock_project/resources/data.json
> +    "errorMsg": "404 - Page Not Found",
```suggestion
    "errorMsg": "<title>v0 by Vercel</title>",
```

2025-02-03 08:00 UTC, ppfeister approved these changes

2025-02-03 08:01 UTC, merged