Adds url_presentation to resources and Add 500px check
sherlock-project/sherlock pull request #848
Opened 2020-11-06 18:21 UTC by omarkdev

Working on 500px, I discovered an API in which I can check the username, but the url presentation is not to good, so I create a "url_presentation" property and add 500px verification.

2020-11-06 18:28 UTC, sdushantha requested changes

2020-11-06 18:28 UTC, sdushantha commented on sherlock/resources/data.json
> +    "url_presentation": "https://500px.com/p/{}",
There is no need to have `url_presentation`. We have a property called `urlProbe` which is used for API endpoints. Then put `https://500px.com/p/{}` in the `url` property

2020-11-07 22:26 UTC, omarkdev commented
@sdushantha Done, I removed the implementation from url_presentation and implements the urlproble

2020-11-07 22:31 UTC, omarkdev commented
@sdushantha The tests are failing, I will close this PR and create other from begin.

2020-11-07 22:31 UTC, closed without merging